renproject/ren-js

- packages/lib/gateway/src/index.ts
- packages/lib/ren-interfaces/src/messages.ts
- packages/ui/gateway-example/src/main.tsx
- packages/ui/gateway.renproject.io/src/state/sdkContainer.tsx
This allows integrators using GatewayJS to store all details of the trade to persistent storage as they are updated.
> Add "transferUpdated" event to GatewayJS

- packages/lib/chains/chains-ethereum/src/base.ts
"error" events from Web3 were being forwarded to the event emitter returned by .mint or .burn, in addition to being caught and thrown. This PR fixes it by removing the event forwarding for errors.
> fix: uncaught web3 rejection

- packages/lib/ren-tx/demos/simpleMint.ts
- packages/lib/ren-tx/src/configs/genericMint.ts
- packages/lib/ren-tx/src/machines/burn.ts
- packages/lib/ren-tx/src/machines/deposit.ts
- packages/lib/ren-tx/src/machines/mint.ts
- packages/lib/ren-tx/src/types/transaction.ts
- packages/lib/ren-tx/test/machines.spec.ts
- packages/lib/ren-tx/test/testutils/mock.ts
This PR improves error handling in ren-tx, giving appropriate error states for different failures. 
Error states either have handlers for recovery, or have no recovery transitions and require a refresh. In future, we can ensure that there are always handlers than enable recovery, or provide a form of fatal failure / manual support instructions at the library level.
> chore(ren-tx): error handling

- packages/lib/chains/chains-ethereum/src/base.ts
- packages/lib/chains/chains-ethereum/src/bsc.ts
- packages/lib/chains/chains-ethereum/test/index.spec.ts
- packages/lib/chains/chains-ethereum/test/utils.spec.ts
This PR updates the Binance Smart Chain's class to provide its own utils instead of inheriting from the Ethereum class.
This ensures that the right network is passed into the explorer url getters.
> fix: bsc explorer links

- packages/lib/ren-tx/src/configs/genericBurn.ts
- packages/lib/ren-tx/src/machines/burn.ts
- packages/lib/ren-tx/src/machines/deposit.ts
- packages/lib/ren-tx/test/machines.spec.ts
Currently, there is a period of time where the burn machine is setting up the `burnAndRelease.burn` instance, where `SUBMIT` events will be ignored.
This introduces a new state `creating` in the burn machine that represents the period before "SUBMIT" events can be handled. UIs should no provide the ability to send this event during this state (see the state chart for valid states where it can be sent)
It also fixes progression until the release stage in the burn machine (would previously be stuck on confirming) and restoring completed burn + mint txs in the 0.3 networks
> fix(ren-tx): resolve timing issue when burning

- packages/lib/ren-tx/src/configs/genericBurn.ts
- packages/lib/ren-tx/src/configs/genericMint.ts
- packages/lib/ren-tx/src/machines/burn.ts
- packages/lib/ren-tx/src/machines/deposit.ts
- packages/lib/ren-tx/src/machines/mint.ts
- packages/lib/ren-tx/src/types/transaction.ts
- packages/lib/ren-tx/test/mint.spec.ts
- packages/lib/ren-tx/test/testutils/mock.ts
- yarn.lock
Previously, we incorrectly used renVM hashes for sourceTxHash when minting,
and destTxHash when burning. This PR adds a new field to track the renVMHash
separately, and provides the correct hashes when possible.
Note, the destTxHash is only available for network 0.3 txs when burning, so 
we currently assume that the burn tx is complete once we receive a renVMHash,
and provide an optional destTxHash for 0.3 txes.
This PR also fixes a newly discovered issue where an incorrect gateway address
provided when creating a mintMachine would never detect txs; we will enter the
"errorInitializing" state now.
> fix(ren-tx): correct txhashes & handle incorrect gateway address

- package.json
- packages/lib/ren-tx/README.md
- packages/lib/ren-tx/demos/simpleMint.ts
- packages/lib/ren-tx/package.json
- packages/lib/ren-tx/src/configs/genericBurn.ts
- packages/lib/ren-tx/src/configs/genericMint.ts
- packages/lib/ren-tx/src/machines/burn.ts
- packages/lib/ren-tx/src/machines/deposit.ts
- packages/lib/ren-tx/src/machines/mint.ts
- packages/lib/ren-tx/test/burn.spec.ts
- packages/lib/ren-tx/test/machines.spec.ts
- packages/lib/ren-tx/test/mint.spec.ts
- packages/lib/ren-tx/test/testutils/mock.ts
- yarn.lock
This refactors the mint and deposit machines so that each deposit does
not need its own renjs lockAndMint instance, routing messages through
the mint machine instead.
> feat(ren tx): single ren js instance

- packages/ui/multiwallet-ui/src/index.tsx
Currently, the MultiWalletModal config object only works with
"testnet"/"mainnet" values; this PR allows all valid RenNetworks
to be accepted.
> fix(multiwallet-ui): handle alternate networks

- packages/lib/interfaces/src/ethArgs.ts
- packages/lib/ren/src/lockAndMint.ts
This PR adds a `onlyInPayload` option for contract call parameters that complements `notInPayload`. It will use the parameter's value for calculating the `pHash` but it won't include it when calling the smart contract.
The use case is for contracts like the WBTC.Cafe curve adapter which include values in the payload hash that aren't passed in directly as contract call parameters - for example `msg.sender`.
> feat(ren-js): add onlyInPayload parameter option

- lerna.json
- packages/lib/chains/chains-bitcoin/package.json
- packages/lib/chains/chains-ethereum/package.json
- packages/lib/chains/chains-filecoin/package.json
- packages/lib/chains/chains-terra/package.json
- packages/lib/chains/chains/package.json
- packages/lib/interfaces/package.json
- packages/lib/multiwallet/multiwallet-abstract-ethereum-connector/package.json
- packages/lib/multiwallet/multiwallet-base-connector/package.json
- packages/lib/multiwallet/multiwallet-binancesmartchain-injected-connector/package.json
- packages/lib/multiwallet/multiwallet-ethereum-injected-connector/package.json
- packages/lib/multiwallet/multiwallet-ethereum-mewconnect-connector/package.json
- packages/lib/multiwallet/multiwallet-ethereum-walletconnect-connector/package.json
- packages/lib/provider/package.json
- packages/lib/ren-tx/package.json
- packages/lib/ren-tx/src/configs/genericBurn.ts
- packages/lib/ren-tx/src/configs/genericMint.ts
- packages/lib/ren-tx/src/machines/deposit.ts
- packages/lib/ren-tx/src/machines/mint.ts
- packages/lib/ren-tx/test/machines.spec.ts
- packages/lib/ren-tx/test/mint.spec.ts
- packages/lib/ren-tx/test/testutils/mock.ts
- packages/lib/ren/package.json
- packages/lib/rpc/package.json
- packages/lib/test/package.json
- packages/lib/utils/package.json
- packages/ui/multiwallet-ui/package.json
Currently, multiple deposits in ren-tx only work if they are processed end to end without restoring.
This fixes the issue by ensuring that machines get individual "RESTORED" events instead of a broadcasting the same event to all deposits
> fix(ren-tx): restore multiple deposits correctly

- packages/lib/chains/chains-ethereum/package.json
- packages/lib/chains/chains-ethereum/src/base.ts
- packages/lib/chains/chains-ethereum/src/utils.ts
- packages/lib/interfaces/src/chain.ts
- packages/lib/ren-tx/test/burn.spec.ts
- packages/lib/ren-tx/test/mint.spec.ts
- packages/lib/ren/src/burnAndRelease.ts
- packages/lib/ren/src/config.ts
- packages/lib/ren/src/index.ts
- packages/lib/ren/src/lockAndMint.ts
- packages/lib/rpc/src/abstract.ts
- packages/lib/rpc/src/combinedProvider.ts
- packages/lib/rpc/src/v1/renVMProvider.ts
- packages/lib/rpc/src/v2/renVMProvider.ts
- yarn.lock
Currently, most repeated network requests use a common timeout of 15 seconds between requests.
This PR makes this timeout configurable. A future update may provide more granular configuration options to configure each type of network request timeout.
> Add config to configure delay when making repeated network requests

- packages/lib/utils/src/common.ts
The 'fromBase64' util function had a call to strip0x that had accidentally been included after copying and modifying the function from 'fromHex'.
> fix(ren-js): remove call to 'strip0x' in 'fromBase64

- packages/lib/multiwallet/multiwallet-ethereum-mewconnect-connector/src/index.ts
- packages/ui/multiwallet-ui/example/index.tsx
- packages/ui/multiwallet-ui/example/yarn.lock
- packages/ui/multiwallet-ui/src/index.tsx
- packages/ui/multiwallet-ui/stories/WalletPickerModal.stories.tsx
This PR allows for the modal to rever to the wallet selection state if the info prop is provided for a wallet, allowing users to select a different wallet based on clarified information.
> feat(multiwallet): return to wallet selection state from connection info state

- packages/lib/multiwallet/multiwallet-ethereum-mewconnect-connector/README.md
- packages/lib/multiwallet/multiwallet-ethereum-mewconnect-connector/src/index.ts
- packages/ui/multiwallet-ui/example/index.tsx
- packages/ui/multiwallet-ui/example/yarn.lock
Previously, MEWConnect only worked on mainnet, but the latest version works on testnet. Also enforces a wss RPC provider, as it fails otherwise
> fix(multiwallet): allow mewconnect to connect to testnets

- packages/lib/multiwallet/multiwallet-binancesmartchain-injected-connector/src/index.ts
Metamask should be used as a separate connector, as it has its own
settings that need to be entered by the user
> fix(multiwallet): Only allow BSC wallet for the BSC injected connector

- packages/lib/chains/chains-ethereum/src/base.ts
- packages/lib/interfaces/src/chain.ts
- packages/lib/ren/src/lockAndMint.ts
Add `withProvider` for updating a chain's provider, and add `mintTransaction` to `LockAndMintDeposit`.
Using `withProvider` allows a website to initialize a LockAndMintDeposit or BurnAndRelease with a read-only provider and then switch to a provider with an unlocked account at the moment of needing to submit a transaction on the relevant chain.
> feat(ren-js): allow updating chain provider

- packages/lib/chains/chains-ethereum/src/base.ts
- packages/lib/interfaces/src/chain.ts
- packages/lib/multiwallet/multiwallet-binancesmartchain-injected-connector/src/index.ts
- packages/lib/multiwallet/multiwallet-ethereum-mewconnect-connector/README.md
- packages/lib/multiwallet/multiwallet-ethereum-mewconnect-connector/src/index.ts
- packages/lib/ren/README.md
- packages/lib/ren/src/lockAndMint.ts
- packages/ui/multiwallet-ui/example/index.tsx
- packages/ui/multiwallet-ui/example/yarn.lock
- packages/ui/multiwallet-ui/src/index.tsx
- packages/ui/multiwallet-ui/stories/WalletPickerModal.stories.tsx
2.1.3 includes the following updates:
1) The BSC injected connector no longer uses `window.ethereum` as a fallback
2) Update the mewconnect connector with testnet support
3) Add `withProvider` to the ren-js chains interface (for switching from a read-only provider to an unlocked provider)
> Release 2.1.3

- lerna.json
- packages/lib/chains/chains-filecoin/package.json
- packages/lib/chains/chains-terra/package.json
- packages/lib/chains/chains-terra/src/api/deposit.ts
- packages/lib/chains/chains-terra/src/api/stakeId.ts
- packages/lib/chains/chains-terra/src/api/terraDev.ts
- packages/lib/chains/chains-terra/src/terra.ts
- packages/lib/chains/chains-terra/src/types/declarations.ts
- packages/lib/chains/chains/package.json
- packages/lib/chains/chains/src/declarations/declarations.d.ts
- packages/lib/test/package.json
This PR updates LUNA support to encode the ghash in the deposit address instead of a memo field.
> feat(ren-js): update LUNA support

- packages/lib/chains/chains-ethereum/src/networks.ts
This PR fixes the configuration for Ethereum so that we can mint/burn Dogecoin on Kovan
> fix(chains): testnetv0.3 has migrated to kovan

- packages/lib/ren-tx/src/configs/genericMint.ts
- packages/lib/ren/src/config.ts
- packages/lib/ren/src/lockAndMint.ts
There are some cases where we may want to fetch deposits that
have already been minted.
This implements that by passing a "loadCompletedDeposits" flag in
the RenJS config object, which will cause all completed deposits to
still trigger the .deposit handler.
The PR also updates ren-tx to handle completed deposits
> feat(ren-js): allow loading completed txes

- packages/lib/chains/chains-bitcoin/src/base.ts
- packages/lib/chains/chains-bitcoin/src/digibyte.ts
- packages/lib/chains/chains-bitcoin/test/addressValidation.spec.ts
- packages/lib/ren/src/burnAndRelease.ts
- packages/lib/ren/src/index.ts
- packages/lib/ren/src/lockAndMint.ts
- packages/lib/test/test/refactor/mint.spec.ts
This PR includes:
1) a fix when decoding bech32 addresses
2) a fix for when the confirmation target is 0
3) an updated testnet explorer link for DGB
> Bech32 fix in Bitcoin.addressStringToBytes

- packages/lib/ren/src/lockAndMint.ts
Currently, RenJS's lockAndMint.signed will skip fetching the signature if it has already been submitted to the mint-chain. This is problematic if the client needs to access the signature or assumes that it will be present.
> fix(ren js): don't skip fetching signature even if already submitted

- packages/lib/ren-tx/src/configs/genericMint.ts
- packages/lib/ren-tx/src/machines/deposit.ts
- packages/lib/ren-tx/src/machines/mint.ts
- packages/lib/ren-tx/test/machines.spec.ts
Currently, we enter the "errorAccepting" state when a transaction cannot be signed.
This is probematic, because some errors can be recovered from, while others cannot.
This PR makes the deposit machine transition into the permanent "rejected" state if a revert is detected, and we can inform users that they should not attempt to retry.
> feat(ren-tx): enter rejected state when tx is reverted

- packages/lib/chains/chains-bitcoin/src/digibyte.ts
One of the digibyte endpoints can no longer be accessed through a browser, so this adds an endpoint to access it through a proxy that also enables CORS.
Note that this means that rate limits may be hit sooner, so we may need to look into spinning up an electrumx node for DigiByte.
> fix(chains-bitcoin): add digibyte endpoint

- packages/lib/ren/src/index.ts
- packages/lib/rpc/src/abstract.ts
- packages/lib/rpc/src/combinedProvider.ts
- packages/lib/rpc/src/v1/renVMProvider.ts
- packages/lib/rpc/src/v2/methods.ts
- packages/lib/rpc/src/v2/methods/ren_queryBlockState.ts
- packages/lib/rpc/src/v2/pack/pack.ts
- packages/lib/rpc/src/v2/renVMProvider.ts
- packages/lib/test/test/refactor/burn.spec.ts
- packages/lib/test/test/refactor/mint.spec.ts
Fees are now tracked in RenVM, so the in-contract fee getters are returning `0`. This PR fixes this by fetching the fees using `ren_queryBlockState`.
> feat: fetch fees from lightnode instead of host-chain

- packages/lib/ren-tx/src/configs/genericMint.ts
- packages/lib/ren-tx/src/machines/burn.ts
- packages/lib/ren-tx/src/machines/deposit.ts
Currently, "out of gas" errors won't be picked up by ren-tx, as we detect the ethereum tx and move into the destInitiated state. This PR fixes that by allowing movement into the errorSubmitting state after a tx has reverted, allowing us to resubmit.
> fix(ren-tx): submit error detection

- packages/lib/chains/chains-filecoin/package.json
- packages/lib/chains/chains-solana/src/index.ts
- packages/lib/chains/chains-solana/src/networks.ts
- packages/lib/interfaces/src/ethArgs.ts
- packages/lib/utils/src/abi.ts
- yarn.lock
Web3 supports structs by passing them in as tuples - but it also expects a `components` array to be provided with a tuple. This PR adds a method to create this `components` array if it wasn't provided.
> Fix support for Ethereum structs and tuples

- packages/lib/chains/chains-ethereum/src/arbitrum.ts
- packages/lib/ren/src/lockAndMint.ts
- packages/lib/rpc/src/abstract.ts
- packages/lib/rpc/src/combinedProvider.ts
Changelog:
* Limit the number of logs fetched from Arbitrum when looking up a mint to 20k logs
> fix(arbitrum): restrict logs requested to 20000

- packages/lib/chains/chains-solana/src/index.ts
- yarn.lock
Currently, the call to `sendAndConfirmRawTransaction` can hang and never resolve, creating a confusing situation for users. This PR adds a timeout of 20s to wait for a transaction to be confirmed, otherwise we consider the broadcast as failed and require a re-submission,
This is not a perfect fix, as there may be cases where the transaction gets broadcast after the timeout; but this will be caught by the simulation when the user tries to re-submit (unless they resubmit instantaneously)
> fix(solana): set max timeout for solana confirmations

- packages/lib/chains/chains-ethereum/package.json
- packages/lib/chains/chains-solana/src/index.ts
- yarn.lock
A recent change affected payloads for Solana mints. This PR undoes that issue, but adds a flag so that existing mints can be handled properly.
> Fix: Add flag for excluding Solana payload

- packages/lib/ren-tx/src/machines/burn.ts
Currently, once the burn machine enters any error states, it cannot recover. This PR adds a "RETRY" event that will retry the release submission. RETRY is not available for errors with burn submission because it may lead to duplicate fund transfers
> fix(rentx): allow for retrying failed burn releases

- packages/chains/chains-solana/src/solanaTxSubmitter.ts
The solana connector was throwing `Cannot read properties of undefined (reading 'numRequiredSignatures')` when passing a Transaction to `simulateTransaction`, so this fix first calls `tx.compileMessage()`
> Fix: Solana `numRequiredSignatures` error

- packages/chains/chains-ethereum/src/arbitrum.ts
- packages/chains/chains-ethereum/src/optimism.ts
> Migrate Optimism and Arbitrum testnets to Goerli
