packages/lib/ren-tx/src/configs/genericBurn.ts
packages/lib/ren-tx/src/configs/genericMint.ts
packages/lib/ren-tx/src/machines/burn.ts
packages/lib/ren-tx/src/machines/mint.ts

Also gradual improvements to ren-tx documentation

feat(ren-tx): only calculate fees if the autoFees flag is set in context

---

packages/ui/multiwallet-ui/src/index.tsx

Customizing label for wallet chain name

WIP: feat(fe) customized wallet chain label

---

packages/lib/ren-tx/demos/simpleMint.ts
packages/lib/ren-tx/src/configs/genericMint.ts
packages/lib/ren-tx/src/machines/burn.ts
packages/lib/ren-tx/src/machines/deposit.ts
packages/lib/ren-tx/src/machines/mint.ts
packages/lib/ren-tx/src/types/transaction.ts
packages/lib/ren-tx/test/machines.spec.ts
packages/lib/ren-tx/test/testutils/mock.ts
packages/ui/multiwallet-ui/example/index.tsx
packages/ui/multiwallet-ui/src/MultiwalletProvider.tsx
packages/ui/multiwallet-ui/test/Multiwallet.test.tsx

Currently, wallets that have been disconnected manually or via some error event will not be able to re-connect.
This fixes that

fix(multiwallet UI): reconnect disconnected wallets

---

packages/lib/ren-tx/src/configs/genericBurn.ts
packages/lib/ren-tx/src/configs/genericMint.ts
packages/lib/ren-tx/src/machines/deposit.ts
packages/lib/ren-tx/test/testutils/mock.ts

This fixes a few issues around restoring deposits, and reporting underlying errors more reliably

fix(ren tx): deposit restoration

---

packages/lib/ren-tx/src/configs/genericBurn.ts
packages/lib/ren-tx/src/machines/burn.ts
packages/lib/ren-tx/src/machines/mint.ts
packages/lib/ren-tx/test/machines.spec.ts

Also fixes an issue when restoring txes that have already
had their burn txes confirmed

fix(ren-tx): release only when burn tx is confirmed

---

packages/lib/chains/chains-bitcoin/src/base.ts
packages/lib/chains/chains-ethereum/src/ethereum.ts
packages/lib/utils/src/common.ts
packages/lib/utils/src/value.ts

fix(ren-js): ensure unit conversions don't return decimals for sats/wei

---

lerna.json
packages/lib/chains/chains-filecoin/package.json
packages/lib/chains/chains-terra/package.json
packages/lib/chains/chains-terra/src/api/deposit.ts
packages/lib/chains/chains-terra/src/api/stakeId.ts
packages/lib/chains/chains-terra/src/api/terraDev.ts
packages/lib/chains/chains-terra/src/terra.ts
packages/lib/chains/chains-terra/src/types/declarations.ts
packages/lib/chains/chains/package.json
packages/lib/chains/chains/src/declarations/declarations.d.ts
packages/lib/test/package.json

Hotfix:
Encode Luna ghash in deposit address

release: 2.1.4

---

packages/ui/multiwallet-ui/src/index.tsx
packages/ui/multiwallet-ui/stories/WalletPickerModal.stories.tsx

This allows for better connecting and info messages in the multiwallet modal

feat(multiwallet): expose wallet name to inner dialogs

---

packages/lib/chains/chains-bitcoin/src/base.ts
packages/lib/chains/chains-bitcoin/src/digibyte.ts
packages/lib/chains/chains-bitcoin/test/addressValidation.spec.ts
packages/lib/chains/chains-ethereum/src/networks.ts
packages/lib/ren-tx/src/configs/genericMint.ts
packages/lib/ren/src/burnAndRelease.ts
packages/lib/ren/src/config.ts
packages/lib/ren/src/index.ts
packages/lib/ren/src/lockAndMint.ts
packages/lib/test/test/refactor/mint.spec.ts
packages/ui/multiwallet-ui/src/index.tsx
packages/ui/multiwallet-ui/stories/WalletPickerModal.stories.tsx

Features:
Loading completed transactions in ren-js and ren-tx (#113)
Multiwallet wallet-name tracking (#111)
Fixes:
Testnet v0.3 kovan migration configuration (#112)

Release: 2.1.6

---

packages/lib/chains/chains-ethereum/src/base.ts
packages/lib/chains/chains-ethereum/src/bsc.ts
packages/lib/chains/chains-ethereum/src/ethereum.ts
packages/lib/chains/chains-ethereum/src/utils.ts
packages/lib/ren/src/lockAndMint.ts
packages/lib/test/test/refactor/mint.spec.ts

This is due to Binance Chain Wallet's RPC having a 5000 block limit

fix(chains-bsc): only check past 5000 blocks

---

packages/lib/chains/chains-bitcoin/src/base.ts
packages/lib/chains/chains-ethereum/src/base.ts

This PR fixes two issues, one that affected all burns from bitcoin forks, and another that affected recovering BSC burns.

feat(chains): fix bech32 address decoding, fix ethereum transaction search

---

lerna.json
packages/lib/chains/chains-bitcoin/package.json
packages/lib/chains/chains-bitcoin/src/base.ts
packages/lib/chains/chains-ethereum/package.json
packages/lib/chains/chains-ethereum/src/base.ts
packages/lib/chains/chains-ethereum/src/bsc.ts
packages/lib/chains/chains-ethereum/src/ethereum.ts
packages/lib/chains/chains-ethereum/src/utils.ts
packages/lib/chains/chains-filecoin/package.json
packages/lib/chains/chains-terra/package.json
packages/lib/chains/chains/package.json
packages/lib/interfaces/package.json
packages/lib/multiwallet/multiwallet-abstract-ethereum-connector/package.json
packages/lib/multiwallet/multiwallet-base-connector/package.json
packages/lib/multiwallet/multiwallet-binancesmartchain-injected-connector/package.json
packages/lib/multiwallet/multiwallet-ethereum-injected-connector/package.json
packages/lib/multiwallet/multiwallet-ethereum-mewconnect-connector/package.json
packages/lib/multiwallet/multiwallet-ethereum-walletconnect-connector/package.json
packages/lib/provider/package.json
packages/lib/ren-tx/package.json
packages/lib/ren/package.json
packages/lib/ren/src/lockAndMint.ts
packages/lib/rpc/package.json
packages/lib/test/package.json
packages/lib/test/test/refactor/mint.spec.ts
packages/lib/utils/package.json
packages/ui/multiwallet-ui/package.json

This has already been released, lets keep master up to date

release: 2.1.8

---

.gitignore
packages/lib/ren-tx/src/configs/genericBurn.ts

The "transaction" parameter should just be a string for restoration

fix(ren-tx): restore burns with sourceTxHash

---

lerna.json
packages/lib/chains/chains-ethereum/package.json
packages/lib/chains/chains-ethereum/src/base.ts
packages/lib/chains/chains-ethereum/src/bsc.ts
packages/lib/chains/chains-ethereum/src/polygon.ts
packages/lib/chains/chains/package.json
packages/lib/multiwallet/multiwallet-abstract-ethereum-connector/package.json
packages/lib/multiwallet/multiwallet-binancesmartchain-injected-connector/package.json
packages/lib/multiwallet/multiwallet-ethereum-injected-connector/package.json
packages/lib/multiwallet/multiwallet-ethereum-mewconnect-connector/package.json
packages/lib/multiwallet/multiwallet-ethereum-walletconnect-connector/package.json
packages/lib/test/package.json
packages/ui/ren-react/package.json

v2.2.2 fixes fetching past logs for Polygon, limited the number of requested logs to 1000.

release: 2.2.2

---

lerna.json
packages/lib/chains/chains-ethereum/package.json
packages/lib/chains/chains-ethereum/src/avalanche.ts
packages/lib/chains/chains-ethereum/src/index.ts
packages/lib/chains/chains/package.json
packages/lib/multiwallet/multiwallet-abstract-ethereum-connector/package.json
packages/lib/multiwallet/multiwallet-binancesmartchain-injected-connector/package.json
packages/lib/multiwallet/multiwallet-ethereum-injected-connector/package.json
packages/lib/multiwallet/multiwallet-ethereum-mewconnect-connector/package.json
packages/lib/multiwallet/multiwallet-ethereum-walletconnect-connector/package.json
packages/lib/ren-tx/package.json
packages/lib/ren-tx/src/configs/genericMint.ts
packages/lib/ren/package.json
packages/lib/test/package.json
packages/ui/ren-react/package.json

This adds support for avalanche, as well as a few minor fixes to burn and mint confirmations

feat(chains): avalanche

---

package.json
packages/lib/chains/chains-filecoin/src/filecoin.ts
packages/lib/chains/chains-solana/src/networks.ts
packages/lib/chains/chains-solana/test/solana.spec.ts
packages/lib/multiwallet/multiwallet-abstract-ethereum-connector/src/index.ts
packages/lib/multiwallet/multiwallet-ethereum-injected-connector/src/index.ts
packages/lib/multiwallet/multiwallet-ethereum-walletconnect-connector/src/index.ts
packages/lib/multiwallet/multiwallet-solana-connector/src/index.ts
packages/lib/ren-tx/demos/simpleMint.ts
packages/lib/ren/package.json
packages/lib/test/test/manualTests/burn.spec.ts
packages/lib/test/test/manualTests/mint.spec.ts
packages/lib/utils/src/abi.ts
packages/lib/utils/test/abi.spec.ts
packages/ui/multiwallet-ui/src/MultiwalletProvider.tsx
packages/ui/ren-react/rollup.config.js
yarn.lock

Changelog:
* properly check if filecoin should point to testnet
* fix lint and test issues to get PR passing

fix: filecoin network check

---

lerna.json
packages/lib/chains/chains-bitcoin/package.json
packages/lib/chains/chains-ethereum/package.json
packages/lib/chains/chains-filecoin/package.json
packages/lib/chains/chains-solana/package.json
packages/lib/chains/chains-terra/package.json
packages/lib/chains/chains/package.json
packages/lib/interfaces/package.json
packages/lib/multiwallet/multiwallet-abstract-ethereum-connector/package.json
packages/lib/multiwallet/multiwallet-base-connector/package.json
packages/lib/multiwallet/multiwallet-binancesmartchain-injected-connector/package.json
packages/lib/multiwallet/multiwallet-ethereum-injected-connector/package.json
packages/lib/multiwallet/multiwallet-ethereum-mewconnect-connector/package.json
packages/lib/multiwallet/multiwallet-ethereum-walletconnect-connector/package.json
packages/lib/multiwallet/multiwallet-solana-connector/package.json
packages/lib/multiwallet/multiwallet-solana-connector/src/index.ts
packages/lib/provider/package.json
packages/lib/ren-tx/package.json
packages/lib/ren/package.json
packages/lib/rpc/package.json
packages/lib/test/package.json
packages/lib/utils/package.json
packages/ui/multiwallet-ui/package.json
packages/ui/playground/index.tsx
packages/ui/playground/multiwallet.ts
packages/ui/ren-react/package.json
yarn.lock

2.4.7 introduced an issue with the multiwallet sollet connector. This PR fixes that

fix(multiwallet): sollet connector

---

packages/lib/chains/chains-solana/src/index.ts

Currently if `solana.getMintParams` is called before the associated token account is created, it will set the `sendTo` field to `"false"`.
Also `this.provider.wallet.publicKey` was being accessed unnecessarily in `getMintParams`.

fix(solana): check that token account has been created

---

lerna.json
packages/lib/chains/chains-ethereum/package.json
packages/lib/chains/chains-ethereum/src/polygon.ts
packages/lib/chains/chains-solana/package.json
packages/lib/chains/chains-solana/src/index.ts
packages/lib/chains/chains/package.json
packages/lib/multiwallet/multiwallet-abstract-ethereum-connector/package.json
packages/lib/multiwallet/multiwallet-binancesmartchain-injected-connector/package.json
packages/lib/multiwallet/multiwallet-ethereum-injected-connector/package.json
packages/lib/multiwallet/multiwallet-ethereum-mewconnect-connector/package.json
packages/lib/multiwallet/multiwallet-ethereum-walletconnect-connector/package.json
packages/lib/ren-tx/package.json
packages/lib/ren/package.json
packages/lib/ren/src/burnAndRelease.ts
packages/lib/test/package.json
packages/lib/test/test/manualTests/burn.spec.ts
packages/lib/test/test/manualTests/mint.spec.ts
packages/ui/ren-react/package.json

Changelog:
* Add retry logic for Solana transaction simulations
* Fix calculating number of confirmations required for burns

Release 2.5.5

---

packages/ren/src/gateway.ts

Changelog:
* Remove a check that disallowed burning with a payload

feat(ren): allow burns with payloads

---

packages/chains/chains-ethereum/src/kava.ts

#209 based off `release/3.4.3`

Kava config updates

---

lerna.json
packages/chains/chains-bitcoin/package.json
packages/chains/chains-ethereum/package.json
packages/chains/chains-ethereum/src/base.ts
packages/chains/chains-ethereum/test/assets.spec.ts
packages/chains/chains-ethereum/test/initialization.spec.ts
packages/chains/chains-ethereum/test/logs.spec.ts
packages/chains/chains-ethereum/test/utils.spec.ts
packages/chains/chains-filecoin/package.json
packages/chains/chains-filecoin/test/explorers.spec.ts
packages/chains/chains-filecoin/test/index.spec.ts
packages/chains/chains-solana/package.json
packages/chains/chains-terra/package.json
packages/chains/chains/package.json
packages/mock-provider/package.json
packages/provider/package.json
packages/provider/src/rpc/jsonRpc.ts
packages/ren/package.json
packages/ren/src/utils/inputAndOutputTypes.ts
packages/utils/package.json
packages/utils/src/common.ts
test/gateway.spec.ts

Changelog:
* Fix MockProvider to support underscores in selector
* Make Ethereum provider parameter optional, defaulting to RPC URL from config

Release 3.5.1: Fix MockProvider to support underscores in selector
